apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /jenkins-data
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins
#   #annotations: 
#    #pv.beta.kubernetes.io/gid: "1000"
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#   - ReadWriteOnce
#   azureFile:
#     secretName: storage-connection
#     secretNamespace: jenkins
#     shareName: {{ .Values.jenkins.azurefileshare }}
#     readOnly: false
#   claimRef:
#     name: jenkins-pvc
#     kind: PersistenVolumeClaim
#     namespace: jenkins
#   persistentVolumeReclaimPolicy: Retain